config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :categories
  resources :images

  resources :users, only: [:new, :show, :create] do
    resources :ideas
  end

  namespace :admin do
    resources :categories, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :images, only: [:new, :create, :edit, :update, :destroy, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :description

  belongs_to :category
  belongs_to :user

  has_many :idea_images, dependent: :destroy
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :url
  
  has_many :idea_images
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  # validates :password_digest, presence: true
  validates :username, presence: true
  has_many :ideas

  has_secure_password

  enum role:[:default, :admin]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only:[:edit, :destroy, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(params[:id])
    @category.save

    redirect_to categories_path
  end

  def edit
  end

  def destroy
    @category.destroy

    redirect_to categories_path
  end

  def update
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)
    @image.save
    redirect_to images_path
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    image = Image.find(params[:id])
    if image.update(image_params)
      redirect_to admin_images_path
    else
      redirect_to edit_admin_image_path(image)
    end
  end

  def destroy
    image = Image.find(params[:id])
    image.destroy
    redirect_to admin_images_path
  end

  private

  def image_params
    params.require(:image).permit(:name, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:destroy, :edit, :update, :show]

  def index
    @user = User.find(params[:user_id])
    @ideas = @user.ideas
  end

  def new
    @user = User.find(params[:user_id])
    @idea = Idea.new
    @categories = Category.all
    @images = Image.all
  end

  def show
    @user = User.find(params[:user_id])
  end


  def create
    @user = User.find(params[:user_id])
    @idea = @user.ideas.new(idea_params)
    idea_image = @idea.idea_images.new(image_params)
    if @idea.save && idea_image.save

      redirect_to user_ideas_path(@user)
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @categories = Category.all
  end

  def update
    @idea.update(idea_params)

    redirect_to user_idea_path(@idea.user, @idea)
  end

  def destroy
    user = User.find(params[:user_id])
    @idea.destroy

    redirect_to user_ideas_path(user)
  end

  private

  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :description, :category_id, :user_id, :image_ids => [])
  end

  def image_params
    params.require(:image).permit(:image_id)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def show
    @image = Image.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
  #logging in and logging out

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = 'Registration failed'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<!-- <% form_for [:admin, category] do |f| %>

<% f.text_field :name %>
<% f.label :name %>

<% f.submit %>
<% end %> -->

app/views/admin/categories/edit.html.erb
<h2>Edit a category for your users</h2>
<%= form_for [:admin, @category] do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit %>
<% end %>

app/views/admin/categories/new.html.erb
<h2>Add a new  category for your users</h2>

<%= form_for [:admin, @category] do |f| %>
<%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/admin/images/new.html.erb
<h2>Add a new image for your users</h2>

<%= form_for [:admin, @image] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit %>
<% end %>

app/views/categories/_form.html.erb
<div id=background >
<%= form_for @category do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>
</div>

app/views/categories/index.html.erb
<h3>All them Categories</h3>
<div id=background >
<% if current_admin? %>
<%= link_to 'Create a new category', new_admin_category_path %>
<% end %>
<ul>
  <% @categories.each do |category| %>
  <li id='category_<%= category.id %>'>
    <%= link_to category.name, category_path(category) %>
    <%= category.name %>
    <% if current_admin? %>
    <%= link_to "Edit", edit_admin_category_path(category) %>
    <%= link_to "Delete", admin_category_path(category), method: "delete" %>
    <% end %>
  </li>
  <% end %>
</ul>
</div>

app/views/categories/new.html.erb
<h1>Create a new category</h1>
<div id=background >
<%= render partial: 'form' %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div id=background >
<% if current_admin? %>
<%= link_to "Edit", edit_admin_category_path(@category) %>
<%= link_to "Delete", admin_category_path(@category), method: "delete" %>
<% end %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id=home >
    <h1> Welcome to IdeaBox </h1>
    <%= link_to 'Sign Up to Be a User', new_user_path %>
  </div>

  </body>
</html>

app/views/ideas/_form.html.erb
<div id=background >
<%= form_for [@user, @idea] do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :category %>
  <%= select(:idea, :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id] }))%>

  <%= f.label :image %>
  <%= select(:image, :image_id, options_for_select(@images.collect { |image| [image.name, image.id] }))%>

  <%= f.submit %>
<% end %>
</div>

app/views/ideas/edit.html.erb
<h2> Edit Idea </h2>
<div id=background >
<%= render partial: "form" %>
</div>

app/views/ideas/index.html.erb
<h3>All them Ideas</h3>

<div id=background >
<ul>
  <% @ideas.each do |idea| %>
  <ol>
    <h3><%= link_to idea.title, user_idea_path(current_user, idea) %></h3>
    <%= idea.description %>
    <%= link_to "Edit", edit_user_idea_path(current_user, idea) %>
    <%= link_to "Delete", user_idea_path(current_user, idea), method: "delete" %>
  </ol>
  <% end %>
</ul>

</div>

app/views/ideas/new.html.erb
<h2> Create a new idea here </h2>
<div id=background >
<%= render partial: "form" %>
</div>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<h3><%= @idea.description %></h3>


<div id=background >
<p> <% @idea.idea_images.each do |idea_image| %></p>
<%= image_tag(idea_image.image.url) %>
<% end %>

</div>

app/views/images/_form.html.erb
<div id=background >
<%= form_for [@user, @image] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.submit %>
<% end %>
</div>

app/views/images/edit.html.erb
<h2> Edit Image </h2>
<div id=background >
<%= render partial: "form" %>
</div>

app/views/images/index.html.erb
 <h3>Check out those images</h3>
 <div id=background >
 <% if current_admin? %>
 <%= link_to 'Create a new image', new_admin_image_path %>
 <% end %>
 <ul>
   <% @images.each do |image| %>
   <li id='image_<%= image.id %>'>
     <%= image_tag(image.url) %>
     <%= link_to image.name, image_path(image) %>
     <% if current_admin? %>
     <%= link_to "Edit", edit_admin_image_path(image) %>
     <%= link_to "Delete", admin_image_path(image), method: "delete" %>
     <% end %>
   </li>
   <% end %>
 </ul>
</div>

app/views/images/new.html.erb
<h1>Add a new Image</h1>
<div id=background >
<%= render partial: "form" %>
</div>

app/views/images/show.html.erb
<h3><%= @image.name %></h3>
<div id=background >
<p> <%= @image.url %></p>
<div id=background >

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav>
  <a href="<%= root_path %>">Home</a>

  <% if current_user %>
    <%= link_to "Log out", logout_path %>
    <%= link_to "Account", user_path(current_user) %>
  <% else %>
    <%= link_to "Register", new_user_path %>
    <%= link_to "I already have an account", login_path %>
  <% end %>
</nav>

app/views/users/new.html.erb
<h1>It's about time you signed up!</h1>
<div id=background >
<%= form_for @user do |f| %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit %>

<% if flash[:error] %>
<%= flash[:error] %>
<% end %>

<% end %>
</div>

app/views/users/show.html.erb
<h1 id='welcome'>Welcome, <%= current_user.username %>!</h1>
<div id=background >
<% if current_admin? %>
<%= link_to 'Create a category', new_admin_category_path %>
<%= link_to 'Create an image', new_admin_image_path %>
<% else %>
<%= link_to 'Create an idea', new_user_idea_path(current_user) %>
<%= link_to 'See all ideas', user_ideas_path(current_user) %>
<% end %>
</div>